### ISSUE TITLE
Code consistency

### ISSUE THREAD

**Issue by erickmx** [AlfredoCU/blog-React#5]
* [ ] When you write a substitution using curly braces isn't necessary to add a space in the middle of the curly braces, like for example:
```jsx
<div>with spaces { 1 + 2 }</div>
```
```jsx
<div>without spaces {1 + 2}</div>
```
```jsx
<div>without any space {1+2}</div>
```
if you will go to add spaces in the curly braces add them in all the code or avoid them, not use them in one file and in other none.
* [ ] When you declare a route using react-router-dom a good practice is to use the property called component giving to you a good readability, don't mix them using functions as components, or as a child component.
```jsx
<Route path="/myroute" exact component={MyComponent} />
```
* [ ] Try to use the property from the component Route called exact, it will go match the exact route you gived, if you don't add it the router will go to match all the routers that have the prefix gived, ignoring the rest of the route and selecting them as valid.

**Comment by AlfredoCU** [comment]
cuidaré de mantener un orden de que todo el code, este igual.
Y haré los cambios en las rutas.
