### ISSUE TITLE
Use bind in components

### ISSUE THREAD

**Issue by erickmx** [AlfredoCU/blog-React#6]
When you declare a class component isn't necessary use bind in functions to avoid the change of context, you can declare the functions using arrow functions and assign them to a class property.
```jsx
// with bind
class MyComponent extends Component {
    constructor(props) {
        super(props);
        this.state = {
            attr1: ""
        };
        this.myFunction = this.myFunctions.bind(this);
    }
    myFunction() {
    }
}
```
```jsx
// without bind
class MyComponent extends Component {
    state = {
        attr1: ""
    };
    myFunction = () => {
    }
}
```
As you can see the other form will go to give you a better readability, and you can optionally add the constructor unless you need to do something in it.

**Comment by AlfredoCU** [comment]
Si es mejor usar arrow functions, tenia que hacer eso por que perdía el contexto.
Lo note al final, sólo tengo un arrow functions y ya no cambie los demás.

**Comment by erickmx** [comment]
All right
